### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by eirnym** [covidgreen/react-native-exposure-notification-service#3]
Please, put a LICENCE file

**Comment by jasnell** [comment]
There is one: https://github.com/covidgreen/react-native-exposure-notification-service/blob/current/LICENSE

**Comment by eirnym** [comment]
I'd like to have this file in each repository for disambiguation

**Comment by eirnym** [comment]
Also it prevents stale links and questions when repository with a license is moved or removed at all.

**Comment by jasnell** [comment]
I'm not sure what you're asking for. The LICENSE file exists in this repository. There is another in the covid-green-app repository. I do believe we need to update this one so that it's fully recognized by GitHub but the license file *does* exist.

**Comment by eirnym** [comment]
I see, it's GitHub who isn't showing it properly

**Comment by jasnell** [comment]
Should be fixed with #5 ... closing this issue in anticipation of that landing
