### ISSUE TITLE
Process to use exposure-notification

### ISSUE THREAD

**Issue by zrg-team** [covidgreen/react-native-exposure-notification-service#33]
I tested on my device it always return:

isSupported => false 

May i register with google or apple to develop ? And how to do it ?

**Comment by zrg-team** [comment]
any help ?

**Comment by colmharte** [comment]
Can you pull latest and try again?

**Comment by zrg-team** [comment]
@colmharte c
I tested with the newest version:

isSupported always return false.

how I enable exposure notification on my device for testing?

**Comment by colmharte** [comment]
is this on iOS or on Android?

**Comment by zrg-team** [comment]
both Android and IOS

**Comment by zrg-team** [comment]
I tested on the example app.
https://github.com/covidgreen/covid-green-app
it still can not enable Exposure Notification

**Comment by colmharte** [comment]
Without an entitlement from Apple or being part of the Google Early Access programme to ENS its not possible to enable exposure notifications locally

**Comment by zrg-team** [comment]
> Without an entitlement from Apple or being part of the Google Early Access programme to ENS its not possible to enable exposure notifications locally

thanks, @colmharte co
we working with Apple and Google
