### ISSUE TITLE
[Question] How does this differ from the HSEIreland organization?

### ISSUE THREAD

**Issue by agmcleod** [covidgreen/react-native-exposure-notification-service#6]
Sorry if inappropriate to ask, but I'm curious as to why it's a copy of the repo on HSEIreland (as well as other repos for that matter). Also doesn't seem to be using the fork feature of github. Is it a re-host to change license?

**Comment by jasnell** [comment]
Yes, it is a re-hosting. The HSE has contributed this code to the Linux Foundation under a new license. It wishes to retain the existing code hosted under the HSEIreland organization as a separate stream for the time being.
