### ISSUE TITLE
Is there any recommended Nodejs flavored API?

### ISSUE THREAD

**Issue by Shashi-GS** [covidgreen/react-native-exposure-notification-service#76]
Hi,

 is there any nodejs flavored API server to use with this application to generate keys?

--
Thanks,
Shashi

**Comment by colmharte** [comment]
Yes have a look at the other repos in Covidgreen, specifically the [backend api ](https://github.com/covidgreen/covid-green-backend-api)and the [Exposure Lambda](https://github.com/covidgreen/covid-green-lambdas/blob/current/exposures.js)
Covid Green is a complete ENS solution, frontend app, ENS integration, backend key server and verification server.
